name: Valid Schema files

on:
  push:
    paths:
      - "schemas/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "schemas/**"
      - ".github/workflows/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Validate schemas
        run: devbox run task test:schemas:validate:story-tests-schema
